export const FETCH_BEGIN   = 'FETCH_BEGIN';
export const FETCH_FAILURE = 'FETCH_FAILURE';

export const FETCH_BOOK_LIST_SUCCESS = 'FETCH_BOOK_LIST_SUCCESS';
export const FETCH_BOOK_SUCCESS = 'FETCH_BOOK_SUCCESS';

export const SET_BOOK = 'SET_BOOK';